// Code generated by Stan version 2.7

#include <stan/model/model_header.hpp>

namespace logistic_model_namespace {

using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::prob_grad;
using namespace stan::math;

typedef Eigen::Matrix<double,Eigen::Dynamic,1> vector_d;
typedef Eigen::Matrix<double,1,Eigen::Dynamic> row_vector_d;
typedef Eigen::Matrix<double,Eigen::Dynamic,Eigen::Dynamic> matrix_d;

static int current_statement_begin__;
class logistic_model : public prob_grad {
private:
    int N;
    vector<int> n;
    vector_d x;
    vector<int> y;
    vector_d f;
public:
    logistic_model(stan::io::var_context& context__,
        std::ostream* pstream__ = 0)
        : prob_grad(0) {
        current_statement_begin__ = -1;

        static const char* function__ = "logistic_model_namespace::logistic_model";
        (void) function__; // dummy call to supress warning
        size_t pos__;
        (void) pos__; // dummy call to supress warning
        std::vector<int> vals_i__;
        std::vector<double> vals_r__;
        context__.validate_dims("data initialization", "N", "int", context__.to_vec());
        N = int(0);
        vals_i__ = context__.vals_i("N");
        pos__ = 0;
        N = vals_i__[pos__++];
        context__.validate_dims("data initialization", "n", "int", context__.to_vec(N));
        validate_non_negative_index("n", "N", N);
        n = std::vector<int>(N,int(0));
        vals_i__ = context__.vals_i("n");
        pos__ = 0;
        size_t n_limit_0__ = N;
        for (size_t i_0__ = 0; i_0__ < n_limit_0__; ++i_0__) {
            n[i_0__] = vals_i__[pos__++];
        }
        validate_non_negative_index("x", "N", N);
        x = vector_d(N);
        context__.validate_dims("data initialization", "x", "vector_d", context__.to_vec(N));
        vals_r__ = context__.vals_r("x");
        pos__ = 0;
        size_t x_i_vec_lim__ = N;
        for (size_t i_vec__ = 0; i_vec__ < x_i_vec_lim__; ++i_vec__) {
            x[i_vec__] = vals_r__[pos__++];
        }
        context__.validate_dims("data initialization", "y", "int", context__.to_vec(N));
        validate_non_negative_index("y", "N", N);
        y = std::vector<int>(N,int(0));
        vals_i__ = context__.vals_i("y");
        pos__ = 0;
        size_t y_limit_0__ = N;
        for (size_t i_0__ = 0; i_0__ < y_limit_0__; ++i_0__) {
            y[i_0__] = vals_i__[pos__++];
        }
        validate_non_negative_index("f", "N", N);
        f = vector_d(N);
        context__.validate_dims("data initialization", "f", "vector_d", context__.to_vec(N));
        vals_r__ = context__.vals_r("f");
        pos__ = 0;
        size_t f_i_vec_lim__ = N;
        for (size_t i_vec__ = 0; i_vec__ < f_i_vec_lim__; ++i_vec__) {
            f[i_vec__] = vals_r__[pos__++];
        }

        // validate data
        check_greater_or_equal(function__,"x",x,0);
        for (int k0__ = 0; k0__ < N; ++k0__) {
            check_greater_or_equal(function__,"y[k0__]",y[k0__],0);
        }
        check_greater_or_equal(function__,"f",f,0);
        check_less_or_equal(function__,"f",f,1);

        double DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning


        // initialize transformed variables to avoid seg fault on val access

        try {
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e,current_statement_begin__);
            // Next line prevents compiler griping about no return
throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }

        // validate transformed data

        // set parameter ranges
        num_params_r__ = 0U;
        param_ranges_i__.clear();
        ++num_params_r__;
        ++num_params_r__;
        ++num_params_r__;
    }

    ~logistic_model() { }


    void transform_inits(const stan::io::var_context& context__,
                         std::vector<int>& params_i__,
                         std::vector<double>& params_r__,
                         std::ostream* pstream__) const {
        stan::io::writer<double> writer__(params_r__,params_i__);
        size_t pos__;
        (void) pos__; // dummy call to supress warning
        std::vector<double> vals_r__;
        std::vector<int> vals_i__;

        if (!(context__.contains_r("b1")))
            throw std::runtime_error("variable b1 missing");
        vals_r__ = context__.vals_r("b1");
        pos__ = 0U;
        context__.validate_dims("initialization", "b1", "double", context__.to_vec());
        double b1(0);
        b1 = vals_r__[pos__++];
        try {
            writer__.scalar_unconstrain(b1);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable b1: ") + e.what());
        }

        if (!(context__.contains_r("b2")))
            throw std::runtime_error("variable b2 missing");
        vals_r__ = context__.vals_r("b2");
        pos__ = 0U;
        context__.validate_dims("initialization", "b2", "double", context__.to_vec());
        double b2(0);
        b2 = vals_r__[pos__++];
        try {
            writer__.scalar_unconstrain(b2);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable b2: ") + e.what());
        }

        if (!(context__.contains_r("b3")))
            throw std::runtime_error("variable b3 missing");
        vals_r__ = context__.vals_r("b3");
        pos__ = 0U;
        context__.validate_dims("initialization", "b3", "double", context__.to_vec());
        double b3(0);
        b3 = vals_r__[pos__++];
        try {
            writer__.scalar_unconstrain(b3);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable b3: ") + e.what());
        }

        params_r__ = writer__.data_r();
        params_i__ = writer__.data_i();
    }

    void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                         std::ostream* pstream__) const {
      std::vector<double> params_r_vec;
      std::vector<int> params_i_vec;
      transform_inits(context, params_i_vec, params_r_vec, pstream__);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r(i) = params_r_vec[i];
    }


    template <bool propto__, bool jacobian__, typename T__>
    T__ log_prob(vector<T__>& params_r__,
                 vector<int>& params_i__,
                 std::ostream* pstream__ = 0) const {

        T__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

        T__ lp__(0.0);
        stan::math::accumulator<T__> lp_accum__;

        // model parameters
        stan::io::reader<T__> in__(params_r__,params_i__);

        T__ b1;
        (void) b1;   // dummy to suppress unused var warning
        if (jacobian__)
            b1 = in__.scalar_constrain(lp__);
        else
            b1 = in__.scalar_constrain();

        T__ b2;
        (void) b2;   // dummy to suppress unused var warning
        if (jacobian__)
            b2 = in__.scalar_constrain(lp__);
        else
            b2 = in__.scalar_constrain();

        T__ b3;
        (void) b3;   // dummy to suppress unused var warning
        if (jacobian__)
            b3 = in__.scalar_constrain(lp__);
        else
            b3 = in__.scalar_constrain();


        // transformed parameters
        Eigen::Matrix<T__,Eigen::Dynamic,1>  theta(N);
        (void) theta;   // dummy to suppress unused var warning
        stan::math::fill(theta,DUMMY_VAR__);

        // initialize transformed variables to avoid seg fault on val access
        stan::math::fill(theta,DUMMY_VAR__);

        try {
            current_statement_begin__ = 17;
            for (int i = 1; i <= N; ++i) {
                current_statement_begin__ = 18;
                stan::math::assign(get_base1_lhs(theta,i,"theta",1), inv_logit(((b1 + (b2 * get_base1(x,i,"x",1))) + (b3 * get_base1(f,i,"f",1)))));
            }
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e,current_statement_begin__);
            // Next line prevents compiler griping about no return
throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }

        // validate transformed parameters
        for (int i0__ = 0; i0__ < N; ++i0__) {
            if (stan::math::is_uninitialized(theta(i0__))) {
                std::stringstream msg__;
                msg__ << "Undefined transformed parameter: theta" << '[' << i0__ << ']';
                throw std::runtime_error(msg__.str());
            }
        }

        const char* function__ = "validate transformed params";
        (void) function__; // dummy to suppress unused var warning
        check_greater_or_equal(function__,"theta",theta,0);

        // model body
        try {
            current_statement_begin__ = 23;
            for (int i = 1; i <= N; ++i) {
                current_statement_begin__ = 24;
                lp_accum__.add(binomial_log<propto__>(get_base1(y,i,"y",1), get_base1(n,i,"n",1), get_base1(theta,i,"theta",1)));
            }
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e,current_statement_begin__);
            // Next line prevents compiler griping about no return
throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }

        lp_accum__.add(lp__);
        return lp_accum__.sum();

    } // log_prob()

    template <bool propto, bool jacobian, typename T_>
    T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
               std::ostream* pstream = 0) const {
      std::vector<T_> vec_params_r;
      vec_params_r.reserve(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        vec_params_r.push_back(params_r(i));
      std::vector<int> vec_params_i;
      return log_prob<propto,jacobian,T_>(vec_params_r, vec_params_i, pstream);
    }


    void get_param_names(std::vector<std::string>& names__) const {
        names__.resize(0);
        names__.push_back("b1");
        names__.push_back("b2");
        names__.push_back("b3");
        names__.push_back("theta");
    }


    void get_dims(std::vector<std::vector<size_t> >& dimss__) const {
        dimss__.resize(0);
        std::vector<size_t> dims__;
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(N);
        dimss__.push_back(dims__);
    }

    template <typename RNG>
    void write_array(RNG& base_rng__,
                     std::vector<double>& params_r__,
                     std::vector<int>& params_i__,
                     std::vector<double>& vars__,
                     bool include_tparams__ = true,
                     bool include_gqs__ = true,
                     std::ostream* pstream__ = 0) const {
        vars__.resize(0);
        stan::io::reader<double> in__(params_r__,params_i__);
        static const char* function__ = "logistic_model_namespace::write_array";
        (void) function__; // dummy call to supress warning
        // read-transform, write parameters
        double b1 = in__.scalar_constrain();
        double b2 = in__.scalar_constrain();
        double b3 = in__.scalar_constrain();
        vars__.push_back(b1);
        vars__.push_back(b2);
        vars__.push_back(b3);

        if (!include_tparams__) return;
        // declare and define transformed parameters
        double lp__ = 0.0;
        (void) lp__; // dummy call to supress warning
        stan::math::accumulator<double> lp_accum__;

        vector_d theta(N);
        (void) theta;   // dummy to suppress unused var warning

        try {
            current_statement_begin__ = 17;
            for (int i = 1; i <= N; ++i) {
                current_statement_begin__ = 18;
                stan::math::assign(get_base1_lhs(theta,i,"theta",1), inv_logit(((b1 + (b2 * get_base1(x,i,"x",1))) + (b3 * get_base1(f,i,"f",1)))));
            }
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e,current_statement_begin__);
            // Next line prevents compiler griping about no return
throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }

        // validate transformed parameters
        check_greater_or_equal(function__,"theta",theta,0);

        // write transformed parameters
        for (int k_0__ = 0; k_0__ < N; ++k_0__) {
            vars__.push_back(theta[k_0__]);
        }

        if (!include_gqs__) return;
        // declare and define generated quantities

        double DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning


        // initialize transformed variables to avoid seg fault on val access

        try {
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e,current_statement_begin__);
            // Next line prevents compiler griping about no return
throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }

        // validate generated quantities

        // write generated quantities
    }

    template <typename RNG>
    void write_array(RNG& base_rng,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                     bool include_tparams = true,
                     bool include_gqs = true,
                     std::ostream* pstream = 0) const {
      std::vector<double> params_r_vec(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r_vec[i] = params_r(i);
      std::vector<double> vars_vec;
      std::vector<int> params_i_vec;
      write_array(base_rng,params_r_vec,params_i_vec,vars_vec,include_tparams,include_gqs,pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i)
        vars(i) = vars_vec[i];
    }

    static std::string model_name() {
        return "logistic_model";
    }


    void constrained_param_names(std::vector<std::string>& param_names__,
                                 bool include_tparams__ = true,
                                 bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        param_name_stream__.str(std::string());
        param_name_stream__ << "b1";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "b2";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "b3";
        param_names__.push_back(param_name_stream__.str());

        if (!include_gqs__ && !include_tparams__) return;
        for (int k_0__ = 1; k_0__ <= N; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "theta" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }

        if (!include_gqs__) return;
    }


    void unconstrained_param_names(std::vector<std::string>& param_names__,
                                   bool include_tparams__ = true,
                                   bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        param_name_stream__.str(std::string());
        param_name_stream__ << "b1";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "b2";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "b3";
        param_names__.push_back(param_name_stream__.str());

        if (!include_gqs__ && !include_tparams__) return;
        for (int k_0__ = 1; k_0__ <= N; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "theta" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }

        if (!include_gqs__) return;
    }

}; // model

} // namespace

typedef logistic_model_namespace::logistic_model stan_model;

